services:
  - type: web
    name: mern-app
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node app.js'
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 3000
